services:
  - type: web
    name: fastmcp-server
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: cd src && python server.py
    plan: free
    autoDeploy: false
    envVars:
      - key: ENVIRONMENT
        value: production
